apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: kiteci-com
  namespace: default
spec:
  domains:
  - kiteci.com
  - www.kiteci.com
  - api.kiteci.com
  - ws.kiteci.com
  acmeUserSecretName: acme-account
  challengeProvider:
    http:
      ingress:
        apiVersion: voyager.appscode.com/v1beta1
        kind: Ingress
        name: voyager-demo
